source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JCUtils_Example', :exclusive => true do
  pod "JCUtils", :path => "../"
end

target 'JCUtils_Tests', :exclusive => true do
  pod "JCUtils", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
